### ISSUE TITLE
Question: Does this still work for you?

### ISSUE THREAD

**Issue by thomersch** [thomaswitt/wise-statement-downloader#1]
Hi! I built something similar to download my Wise statements, but it stopped working for me a few months back. There is some ominous message in the Wise interface that public key SCA is not available due to PSD2. Thus my question: Does this still work for you or is it just me?

**Comment by thomaswitt** [comment]
@thomersch Just tried it, my script works perfectly fine.

I still also can manage my public keys at <https://wise.com/settings/public-keys> and my API tokens at <https://wise.com/settings/apitokens-settings>

**Comment by thomaswitt** [comment]
@thomersch Did you try to contact Wise support?

**Comment by thomersch** [comment]
Yeah, I did. Apparently public key auth is only available with business accounts now, not anymore with personal ones.
