### ISSUE TITLE
getting zero byte files

### ISSUE THREAD

**Issue by gingerlime** [thomaswitt/wise-statement-downloader#2]
Thanks for creating this bash script!

I set it up and it seems to connect and shows my wise accounts and years, and looks like it's downloading stuff, but all files are zero bytes

![CleanShot 2024-07-15 at 20 42 06](https://github.com/user-attachments/assets/5f6b7e47-fce8-4615-8f88-04afed194c3e)

![CleanShot 2024-07-15 at 20 43 55](https://github.com/user-attachments/assets/87919144-e7cb-4a4a-b23e-7b0f5786cfb4)

Any tips how to debug it?

**Comment by thomaswitt** [comment]
Go into the perform_request function and uncomment the echo debugs. Run the curl requests manually afterwards

**Comment by gingerlime** [comment]
I'm getting 403 back from the API, the curl requests look ok, but it's hard for me to debug the specific headers etc.

**Comment by thomaswitt** [comment]
I would say most likely your 2FA pem file which is wrong/missing/incorrect. API key seems to work otherwise you wouldnt get the menu.

**Comment by gingerlime** [comment]
```
curl -s -H "x-2fa-approval: ***************" -H "X-Signature: ********==" -D - -H "Authorization: Bearer ************" -H "Content-Type: application/json" https://api.transferwise.com/v1/profiles/******/balance-statements/*****/statement.csv?intervalStart=2024-01-01T00:00:00.000Z\&intervalEnd=2024-12-31T23:59:59.999Z\&type=COMPACT
HTTP/2 403
date: Tue, 16 Jul 2024 14:22:40 GMT
content-type: text/csv
content-length: 0
x-2fa-approval: 6c013ae7-3787-4d0e-9034-9720bff3cb62
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
x-content-type-options: nosniff
x-xss-protection: 0
x-2fa-approval-result: REJECTED
x-frame-options: DENY
expires: 0
x-trace-id: beafb55f27f1c43
x-envoy-upstream-service-time: 80
x-envoy-attempt-count: 1
vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
cf-cache-status: MISS
set-cookie: __cf_bm=2RMrOhfxrqfq_xGhoGoW3xhwIUqysIE.yb9mPWSmjmI-1721139760-1.0.1.1-I0qtBnBZYZNZL45kqQtdJqw1oj.YZblOGRY0_mG4oMAi._ElVU6p64etMx.PHuPz3XpsqZD5kKbAhNS_7PU61xOplCA_liDbygk5idug4b0; path=/; expires=Tue, 16-Jul-24 14:52:40 GMT; domain=.transferwise.com; HttpOnly; Secure; SameSite=None
strict-transport-security: max-age=31536000
server: cloudflare
cf-ray: 8a42a54cdf2ac403-WAW
alt-svc: h3=":443"; ma=86400
```

**Comment by gingerlime** [comment]
The API key should be correct, because it fetches the account info?

The pem file was generated based on your instructions.

**Comment by thomaswitt** [comment]
The line
```
x-2fa-approval-result: REJECTED
```
says that my assumption is most likely right.

**Comment by gingerlime** [comment]
I regenerated the pem files, but still getting the same issue unfortunately.

**Comment by gingerlime** [comment]
maybe some accounts are blocked due to SCA ? https://docs.wise.com/api-docs/features/strong-customer-authentication-2fa/personal-token-sca

**Comment by thomaswitt** [comment]
Haven't seen that notice before. Maybe, yes. In any case, I can confirm that my script works well on a Wise Business Account with existing keys, just tested 2 minutes ago.

**Comment by gingerlime** [comment]
Unfortunately it doesn't work for me :( But well, it was worth a shot.

**Comment by thomaswitt** [comment]
@gingerlime Did you try to contact Wise support?

**Comment by gingerlime** [comment]
Funnily enough, I just contacted them a few days ago. They didn't help at all. The only thing they were saying is to download manually on their website.
